
spring:
  application:
    name: app
  jpa:
    generate-ddl: true
    show-sql: true
  output:
    ansi:
      enabled: always

logging:
  level:
    root: WARN

server:
  address: 0.0.0.0
  port: ${PORT:8080}