spring:
  application:
    name: app
  jpa:
    generate-ddl: true
    hibernate:
      show-sql: true
  output:
    ansi:
      enabled: always

rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem

logging:
  level:
    root: WARN
    org:
      springframework:
        # web: DEBUG
        security: DEBUG

server:
  address: 0.0.0.0
  port: ${PORT:8080}
